import { Form, Head, Link } from '@inertiajs/react';
import { useEffect, useState } from 'react';
import AppLayout from '../../layouts/app-layout';
import FormField from '../../components/form-field';

type Family = { id:number; external_family_id:string|null; manual_reference:string|null; head_name:string; head_mobile?:string|null };
type Assignment = { id:number; slot_number:number; assignment_type:string; assignment_source:string; family:Family; home_visit?:{id:number;karyakar_id:number;completed_at:string;is_admin_override:boolean}|null };
type KAssignment = { id:number; position:number; karyakar:{id:number; full_name:string; gender:string; category:string; mobile?:string|null; karyakar_reference:string} };
type RemainingReport={id:number;status:string;note?:string|null;reported_at?:string|null;review_note?:string|null;family:Family & {address?:string|null;city_village?:string|null;status:string};karyakar:{id:number;full_name:string;karyakar_reference:string}};
type Group = { id:number; group_code:string; group_type:string; status:string; center:{id:number;name:string;code:string}; area?:{id:number;name:string}|null; society?:{id:number;name:string}|null; karyakar_assignments:KAssignment[]; family_assignments:Assignment[]; remaining_family_reports:RemainingReport[] };
type Props = { group:Group; composition:{total:number;fixed:number;remaining:number;completed:number;pending:number;slotsLeft:number;canActivate:boolean}; eligibleFamilies:Family[]; transferGroups:{id:number;group_code:string;status:string;active_families_count:number}[]; areas:{id:number;name:string}[]; societies:{id:number;sampark_area_id:number;name:string}[]; canAdminAssign:boolean; canManageFixed:boolean; canTransferFamilies:boolean; canAssignArea:boolean; canActivate:boolean; canSelectRemaining:boolean };
const typeLabel=(v:string)=>({couple:'Husband + Wife / Couple',two_male:'2 Male',two_female:'2 Female'}[v]??v);

export default function GroupDetail({group,composition,eligibleFamilies,transferGroups,areas,societies,canAdminAssign,canManageFixed,canTransferFamilies,canAssignArea,canActivate,canSelectRemaining}:Props){
    const [areaId,setAreaId]=useState(String(group.area?.id??areas[0]?.id??''));
    const [familySearch,setFamilySearch]=useState('');
    const [familyOptions,setFamilyOptions]=useState<Family[]>(eligibleFamilies);
    const [familySearchError,setFamilySearchError]=useState('');
    const [selectedFamilyIds,setSelectedFamilyIds]=useState<number[]>([]);
    const availableSocieties=societies.filter(s=>String(s.sampark_area_id)===areaId);
    useEffect(()=>{
        if(!(canAdminAssign||canSelectRemaining)||group.status==='active'){setFamilyOptions([]);return;}
        const timer=window.setTimeout(()=>{
            fetch(`/assignments/groups/${group.id}/families/search?${new URLSearchParams({q:familySearch}).toString()}`,{headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest'},credentials:'same-origin'})
                .then(async response=>{if(!response.ok)throw new Error(String(response.status));return response.json() as Promise<{results:Family[]}>})
                .then(data=>{const assigned=new Set(group.family_assignments.map(a=>a.family.id));setFamilyOptions(data.results.filter(f=>!assigned.has(f.id)));setSelectedFamilyIds(ids=>ids.filter(id=>!assigned.has(id)));setFamilySearchError('')})
                .catch(()=>setFamilySearchError('Could not load eligible Families. Please retry.'));
        },250);
        return()=>window.clearTimeout(timer);
    },[familySearch,group.id,group.status,canAdminAssign,canSelectRemaining,composition.total]);
    const assignedFamilyIds=new Set(group.family_assignments.map(a=>a.family.id));
    const unassignedFamilyOptions=familyOptions.filter(f=>!assignedFamilyIds.has(f.id));
    const toggleFamily=(id:number)=>setSelectedFamilyIds(current=>current.includes(id)?current.filter(x=>x!==id):(current.length<composition.slotsLeft?[...current,id]:current));
    return <AppLayout title={`Group ${group.group_code}`}><Head title={group.group_code}/><div className="space-y-5">
        <section className="hf-card p-5"><div className="flex flex-wrap justify-between gap-4"><div><Link href="/assignments/groups" className="text-sm font-bold text-[#6a1b9a]">← All Groups</Link><h2 className="text-2xl font-black mt-2">{group.group_code}</h2><p className="text-sm text-[#76647e]">{group.center.name} · {typeLabel(group.group_type)}</p></div><div className="flex items-start gap-2"><span className="hf-badge capitalize">{group.status}</span><span className="hf-badge">{composition.total}/10 Families</span></div></div>
            <div className="grid gap-3 mt-5 sm:grid-cols-2 lg:grid-cols-6">{[['Karyakars','2 / 2'],['Families',`${composition.total} / 10`],['Fixed',`${composition.fixed} / 5-6`],['Remaining',`${composition.remaining} / 4-5`],['Completed',composition.completed],['Pending',composition.pending]].map(([a,b])=><div key={String(a)} className="rounded-xl bg-[#faf5fc] p-4"><div className="text-xs font-bold text-[#76647e]">{a}</div><div className="text-xl font-black text-[#641c7d] mt-1">{b}</div></div>)}</div>
        </section>

        <div className="grid gap-5 lg:grid-cols-[.75fr_1.25fr]">
            <section className="hf-card p-5"><h2 className="font-extrabold text-lg">2 Sankalp Karyakars</h2><div className="space-y-3 mt-4">{group.karyakar_assignments.map(a=><div key={a.id} className="rounded-xl border border-[#eadff0] p-4"><div className="flex justify-between gap-3"><b>{a.position}. {a.karyakar.full_name}</b><span className="hf-badge capitalize">{a.karyakar.gender}</span></div><div className="text-sm text-[#76647e] mt-1">{a.karyakar.karyakar_reference} · {a.karyakar.category}</div>{a.karyakar.mobile&&<a className="text-sm font-bold text-[#6a1b9a] mt-2 inline-block" href={`tel:${a.karyakar.mobile}`}>{a.karyakar.mobile}</a>}</div>)}</div></section>
            <section className="hf-card p-5 overflow-x-auto"><h2 className="font-extrabold text-lg">10 Family Slots</h2><p className="text-sm text-[#76647e] mb-4">Fixed/Locked Families are administrative assignments. Remaining Families may be selected by assigned Karyakars.</p><div className="hf-table-scroll"><table className="hf-table hf-mobile-table min-w-[760px]"><thead><tr><th>Slot</th><th>Family</th><th>Type</th><th>Visit</th><th>Source</th><th>Transfer</th></tr></thead><tbody>{group.family_assignments.map(a=><tr key={a.id}><td>{a.slot_number}</td><td><b>{a.family.external_family_id??a.family.manual_reference}</b><div className="text-xs">{a.family.head_name}</div>{a.family.head_mobile&&<a href={`tel:${a.family.head_mobile}`} className="mt-1 inline-block text-xs font-bold text-[#6a1b9a]">Call {a.family.head_mobile}</a>}</td><td><span className="hf-badge">{a.assignment_type==='fixed'?'Fixed / Locked':'Remaining'}</span></td><td>{a.home_visit?<><span className="rounded-full bg-green-100 px-2 py-1 text-xs font-bold text-green-800">Completed</span><div className="mt-1 text-xs text-[#76647e]">{new Date(a.home_visit.completed_at).toLocaleString()}{a.home_visit.is_admin_override?' · override':''}</div></>:<span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-bold text-amber-900">Pending</span>}</td><td className="capitalize">{a.assignment_source}</td><td>{canTransferFamilies&&transferGroups.length>0?<Form action={`/assignments/groups/${group.id}/families/${a.id}/transfer`} method="post" className="flex flex-wrap gap-1 items-center"><select name="destination_group_id" className="hf-input !w-auto text-xs" required><option value="">Destination</option>{transferGroups.filter(g=>g.active_families_count<10).map(g=><option key={g.id} value={g.id}>{g.group_code} ({g.active_families_count}/10)</option>)}</select><select name="assignment_type" className="hf-input !w-auto text-xs" defaultValue={a.assignment_type}><option value="fixed">Fixed</option><option value="remaining">Remaining</option></select><input name="reason" className="hf-input !w-40 text-xs" placeholder="Reason required" required/><button className="hf-btn !py-2 text-xs">Transfer</button></Form>:<span className="text-xs text-[#76647e]">-</span>}</td></tr>)}</tbody></table></div>{composition.total===0&&<div className="text-sm text-[#76647e] py-6 text-center">No Families assigned yet.</div>}</section>
        </div>

        <div className="grid gap-5 lg:grid-cols-2">
            {canAdminAssign&&group.status!=='active'&&<section className="hf-card p-5"><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="font-extrabold text-lg">Assign Families</h2><p className="text-sm text-[#76647e]">Select one or multiple currently unassigned Families. Already assigned Families are removed from this list; transfers are done only from the Family Slots table above.</p></div><span className="hf-badge">{composition.slotsLeft} slots left</span></div><Form action={`/assignments/groups/${group.id}/families`} method="post" className="space-y-3 mt-4" onSuccess={()=>setSelectedFamilyIds([])}>{({errors,processing})=><><FormField label="Find Family"><input className="hf-input" value={familySearch} onChange={e=>setFamilySearch(e.target.value)} placeholder="Family ID / head name"/></FormField>{familySearchError&&<p className="text-xs text-red-700">{familySearchError}</p>}<FormField label={`Unassigned Sankalp Families (${selectedFamilyIds.length} selected)`} error={errors.family_ids}><div className="max-h-64 space-y-1 overflow-y-auto rounded-xl border border-[#dfcfe6] bg-white p-2">{unassignedFamilyOptions.length===0?<div className="p-3 text-sm text-[#76647e]">No unassigned Families match this search.</div>:unassignedFamilyOptions.map(f=>{const checked=selectedFamilyIds.includes(f.id);const disabled=!checked&&selectedFamilyIds.length>=composition.slotsLeft;return <label key={f.id} className={`flex cursor-pointer items-start gap-3 rounded-lg p-2 text-sm ${checked?'bg-[#f4eafa]':'hover:bg-[#faf7fc]'} ${disabled?'opacity-50':''}`}><input type="checkbox" checked={checked} disabled={disabled} onChange={()=>toggleFamily(f.id)} className="mt-1"/><span><b>{f.external_family_id??f.manual_reference}</b><span className="block text-xs text-[#76647e]">{f.head_name}{f.head_mobile?` · ${f.head_mobile}`:''}</span></span></label>})}</div>{selectedFamilyIds.map(id=><input key={id} type="hidden" name="family_ids[]" value={id}/>)}</FormField><FormField label="Assignment Type" error={errors.assignment_type}><select name="assignment_type" className="hf-input">{canManageFixed&&<option value="fixed">Fixed / Locked</option>}{canTransferFamilies&&<option value="remaining">Remaining</option>}</select></FormField><FormField label="Change note (optional)"><input name="change_note" className="hf-input"/></FormField><button className="hf-btn w-full" disabled={processing||composition.slotsLeft===0||selectedFamilyIds.length===0}>Assign {selectedFamilyIds.length||''} {selectedFamilyIds.length===1?'Family':'Families'}</button></>}</Form></section>}
            {canSelectRemaining&&group.status!=='active'&&<section className="hf-card p-5"><h2 className="font-extrabold text-lg">Select Existing Remaining Family</h2><p className="text-sm text-[#76647e] mb-4">For an assigned Karyakar. The selection is recorded as Remaining and visible to Center Admin.</p><Form action={`/assignments/groups/${group.id}/remaining-family`} method="post" className="space-y-3"><FormField label="Find Family"><input className="hf-input" value={familySearch} onChange={e=>setFamilySearch(e.target.value)} placeholder="Family ID / head name"/></FormField>{familySearchError&&<p className="text-xs text-red-700">{familySearchError}</p>}<FormField label="Unassigned Sankalp Family"><select name="family_id" className="hf-input" required><option value="">Select Family</option>{unassignedFamilyOptions.map(f=><option key={f.id} value={f.id}>{f.external_family_id??f.manual_reference} - {f.head_name}</option>)}</select></FormField><FormField label="Note"><input name="change_note" className="hf-input" placeholder="Optional note for Center Admin"/></FormField><button className="hf-btn w-full">Select Remaining Family</button></Form></section>}
        </div>

        {canSelectRemaining&&group.status!=='active'&&<section className="hf-card p-5"><h2 className="font-extrabold text-lg">Report New Remaining Family</h2><p className="text-sm text-[#76647e] mb-4">Use this when the Family is not yet in the portal. The record stays Pending Verification until an authorized admin accepts or rejects it.</p><Form action={`/assignments/groups/${group.id}/remaining-family/report`} method="post" className="grid gap-3 md:grid-cols-2">{({errors,processing})=><><FormField label="Head of Family" error={errors.head_name}><input name="head_name" className="hf-input" required/></FormField><FormField label="Mobile"><input name="head_mobile" className="hf-input" inputMode="numeric" maxLength={10} pattern="[6-9][0-9]{9}" placeholder="10-digit mobile"/></FormField><FormField label="City / Village"><input name="city_village" className="hf-input"/></FormField><FormField label="Address"><input name="address" className="hf-input"/></FormField><div className="md:col-span-2"><FormField label="Note for Center Admin"><textarea name="note" className="hf-input" rows={2}/></FormField></div><div className="md:col-span-2"><button className="hf-btn w-full" disabled={processing}>Report New Family for Verification</button></div></>}</Form></section>}

        {canTransferFamilies&&group.remaining_family_reports?.length>0&&<section className="hf-card p-5 overflow-x-auto"><h2 className="font-extrabold text-lg">Remaining Family Reports</h2><p className="text-sm text-[#76647e] mb-4">Accepting a pending report activates the Family record and assigns it as Remaining, subject to Group capacity and duplicate-assignment rules.</p><div className="hf-table-scroll"><table className="hf-table hf-mobile-table min-w-[900px]"><thead><tr><th>Family</th><th>Reported By</th><th>Status</th><th>Note</th><th>Review</th></tr></thead><tbody>{group.remaining_family_reports.map(r=><tr key={r.id}><td><b>{r.family.manual_reference}</b><div className="text-xs">{r.family.head_name} {r.family.head_mobile?`· ${r.family.head_mobile}`:''}</div></td><td>{r.karyakar.full_name}<div className="text-xs">{r.karyakar.karyakar_reference}</div></td><td><span className="hf-badge capitalize">{r.status}</span></td><td>{r.note??'-'}</td><td>{r.status==='pending'?<div className="space-y-2"><Form action={`/assignments/groups/${group.id}/remaining-family-reports/${r.id}/review`} method="post" className="flex gap-2"><input type="hidden" name="decision" value="accepted"/><input name="review_note" className="hf-input" placeholder="Review note"/><button className="hf-btn !py-2 text-xs">Accept + Assign</button></Form><Form action={`/assignments/groups/${group.id}/remaining-family-reports/${r.id}/review`} method="post" className="flex gap-2"><input type="hidden" name="decision" value="rejected"/><input name="review_note" className="hf-input" placeholder="Reason"/><button className="hf-btn hf-btn-secondary !py-2 text-xs">Reject</button></Form></div>:<span className="text-xs">{r.review_note??'Reviewed'}</span>}</td></tr>)}</tbody></table></div></section>}

        <div className="grid gap-5 lg:grid-cols-2">
            {canAssignArea&&<section className="hf-card p-5"><h2 className="font-extrabold text-lg">Group Area / Society</h2><p className="text-sm text-[#76647e] mb-2">Current: {group.area?.name??'Unassigned'}{group.society?` / ${group.society.name}`:''}</p><p className="mb-4 text-xs text-[#76647e]">Assign it here for this Group, or use the Sampark Area & Society menu for Group/Karyakar/Family assignments.</p>{areas.length===0&&<div className="mb-3 rounded-lg bg-amber-50 p-3 text-xs font-semibold text-amber-800">No Sampark Area master is available for this Center. Create it in Settings / Master Data first.</div>}<Form action="/assignments/areas" method="post" className="space-y-3"><input type="hidden" name="record_type" value="group"/><input type="hidden" name="record_id" value={group.id}/><FormField label="Sampark Area"><select name="sampark_area_id" className="hf-input" value={areaId} onChange={e=>setAreaId(e.target.value)} required>{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></FormField><FormField label="Society"><select name="society_id" className="hf-input"><option value="">No Society</option>{availableSocieties.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></FormField><FormField label="Reason / Change note"><input name="reason" className="hf-input" required placeholder="Why is this assignment being set/changed?"/></FormField><button className="hf-btn w-full" disabled={areas.length===0}>Update Area / Society</button></Form></section>}
            <section className="hf-card p-5"><h2 className="font-extrabold text-lg">Activation Gate</h2><p className="text-sm text-[#76647e] mt-2">Activation is allowed only when the Group has exactly 2 approved Karyakars, exactly 10 active Families, 5-6 Fixed/Locked and 4-5 Remaining.</p><div className="mt-4 rounded-xl p-4 bg-[#faf5fc]"><b>{composition.canActivate?'Composition valid':'Composition incomplete'}</b><div className="text-sm mt-1">Fixed {composition.fixed}; Remaining {composition.remaining}; Total {composition.total}.</div></div>{canActivate&&group.status!=='active'&&<Form action={`/assignments/groups/${group.id}/activate`} method="post" className="mt-4"><button className="hf-btn w-full" disabled={!composition.canActivate}>Activate Group</button></Form>}</section>
        </div>
    </div></AppLayout>;
}
