import { Head, useForm } from '@inertiajs/react';
import AppLayout from '../../layouts/app-layout';

export default function Announcements({announcements,centers,canManage}:any){
 const f=useForm({center_id:'',title:'',body:'',audience:'all',status:'published',published_at:'',expires_at:''});
 return <AppLayout title="Announcements"><Head title="Announcements"/><div className={canManage?'grid gap-5 xl:grid-cols-[420px_1fr]':''}>
  {canManage&&<form className="hf-card p-5 space-y-3" onSubmit={e=>{e.preventDefault();f.post('/support/announcements',{onSuccess:()=>f.reset('title','body','expires_at')})}}><h2 className="text-lg font-extrabold">Publish announcement</h2><Field label="Center scope"><select className="hf-input" value={f.data.center_id} onChange={e=>f.setData('center_id',e.target.value)}><option value="">All Centers</option>{centers.map((c:any)=><option key={c.id} value={c.id}>{c.code} - {c.name}</option>)}</select></Field><Field label="Title"><input className="hf-input" value={f.data.title} onChange={e=>f.setData('title',e.target.value)}/></Field><Field label="Announcement"><textarea className="hf-input min-h-32" value={f.data.body} onChange={e=>f.setData('body',e.target.value)}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Audience"><select className="hf-input" value={f.data.audience} onChange={e=>f.setData('audience',e.target.value)}><option value="all">All</option><option value="main">Main Project</option><option value="bal">Bal Pravruti</option></select></Field><Field label="Status"><select className="hf-input" value={f.data.status} onChange={e=>f.setData('status',e.target.value)}><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></Field></div><Field label="Expires at (optional)"><input type="datetime-local" className="hf-input" value={f.data.expires_at} onChange={e=>f.setData('expires_at',e.target.value)}/></Field>{Object.values(f.errors).length>0&&<div className="hf-error">{Object.values(f.errors).join(' ')}</div>}<button className="hf-btn" disabled={f.processing}>Save Announcement</button></form>}
  <section className="space-y-4">{announcements.length===0?<div className="hf-card p-6 text-sm text-[#78677e]">No announcements available.</div>:announcements.map((a:any)=><article key={a.id} className="hf-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><span className="hf-badge">{a.center?.code??'All Centers'}</span><span className="hf-badge">{a.audience}</span>{canManage&&<span className="hf-badge">{a.status}</span>}</div><h2 className="mt-3 text-xl font-black text-[#4b155f]">{a.title}</h2></div><div className="text-xs text-[#78677e]">{a.published_at?new Date(a.published_at).toLocaleString():''}</div></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#4e4054]">{a.body}</p>{a.expires_at&&<div className="mt-3 text-xs font-semibold text-[#876a8f]">Available until {new Date(a.expires_at).toLocaleString()}</div>}</article>)}</section>
 </div></AppLayout>
}
function Field({label,children}:{label:string;children:any}){return <div><label className="hf-label">{label}</label>{children}</div>}
