import { Head, router, useForm } from '@inertiajs/react';
import AppLayout from '../../layouts/app-layout';
import { Share2, ExternalLink } from 'lucide-react';

export default function Content({contents,centers,canManage,types,filters}:any){
 const f=useForm<any>({center_id:'',content_type:'quote',title:'',body:'',url:'',media_file:null,audience:'all',status:'published',sort_order:0,published_at:'',expires_at:''});
 const share=async(c:any)=>{const url=c.url||c.file_url||window.location.href;const data={title:c.title,text:c.body||c.title,url};if(navigator.share){await navigator.share(data).catch(()=>{})}else{await navigator.clipboard?.writeText(url)}};
 const motivations=contents.filter((c:any)=>c.content_type==='motivation');
 return <AppLayout title="Karyalay Shared Content"><Head title="Shared Content"/>{motivations.length>0&&<section className="hf-card mb-5 overflow-hidden"><div className="hf-brand px-5 py-3 text-white"><div className="text-xs font-bold uppercase tracking-[.16em] opacity-80">Project Motivation</div><h2 className="text-lg font-black">Motivation Slider</h2></div><div className="flex snap-x gap-4 overflow-x-auto p-4">{motivations.map((m:any)=><article key={`mot-${m.id}`} className="min-w-[280px] max-w-[420px] snap-start rounded-2xl bg-[#faf5fc] p-5 md:min-w-[380px]"><span className="hf-badge">{m.center?.code??'All Centers'}</span><h3 className="mt-3 text-xl font-black text-[#5f187c]">{m.title}</h3><p className="mt-2 text-sm leading-6 text-[#5d4b63]">{m.body}</p>{(m.url||m.file_url)&&<a target="_blank" rel="noreferrer" href={m.url||m.file_url} className="mt-3 inline-flex font-bold text-[#6a1b9a]">Open motivation content</a>}</article>)}</div></section>}<div className="mb-5 flex flex-wrap gap-2"><button className={`hf-btn ${!filters.type?'':'hf-btn-secondary'}`} onClick={()=>router.get('/support/content')}>All</button>{types.map((t:string)=><button key={t} className="hf-btn hf-btn-secondary capitalize" onClick={()=>router.get('/support/content',{type:t},{preserveState:true})}>{t}</button>)}</div><div className={canManage?'grid gap-5 xl:grid-cols-[420px_1fr]':''}>
 {canManage&&<form className="hf-card p-5 space-y-3" onSubmit={e=>{e.preventDefault();f.post('/support/content',{forceFormData:true,onSuccess:()=>f.reset('title','body','url','media_file','expires_at')})}}><h2 className="text-lg font-extrabold">Add shared content</h2><div className="grid grid-cols-2 gap-3"><Field label="Type"><select className="hf-input" value={f.data.content_type} onChange={e=>f.setData('content_type',e.target.value)}>{types.map((t:string)=><option key={t} value={t}>{t}</option>)}</select></Field><Field label="Center"><select className="hf-input" value={f.data.center_id} onChange={e=>f.setData('center_id',e.target.value)}><option value="">All</option>{centers.map((c:any)=><option key={c.id} value={c.id}>{c.code}</option>)}</select></Field></div><Field label="Title"><input className="hf-input" value={f.data.title} onChange={e=>f.setData('title',e.target.value)}/></Field><Field label="Text / Caption"><textarea className="hf-input min-h-28" value={f.data.body} onChange={e=>f.setData('body',e.target.value)}/></Field><Field label="External link"><input className="hf-input" placeholder="https://..." value={f.data.url} onChange={e=>f.setData('url',e.target.value)}/></Field><Field label="Media file (PDF/video/audio/image)"><input type="file" className="hf-input" onChange={e=>f.setData('media_file',e.target.files?.[0]??null)}/></Field><button className="hf-btn" disabled={f.processing}>Publish Content</button>{Object.values(f.errors).length>0&&<div className="hf-error">{Object.values(f.errors).join(' ')}</div>}</form>}
 <section className="grid gap-4 md:grid-cols-2">{contents.map((c:any)=><article key={c.id} className="hf-card overflow-hidden"><div className="hf-brand px-5 py-3 text-white flex justify-between gap-3"><span className="font-extrabold capitalize">{c.content_type}</span><span className="text-xs opacity-85">{c.center?.code??'All Centers'}</span></div><div className="p-5"><h2 className="text-lg font-black">{c.title}</h2>{c.body&&<p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#5d4b63]">{c.body}</p>}{(c.url||c.file_url)&&<a target="_blank" rel="noreferrer" href={c.url||c.file_url} className="mt-4 inline-flex items-center gap-2 font-bold text-[#6a1b9a]"><ExternalLink size={16}/> Open content</a>}<button onClick={()=>share(c)} className="mt-4 ml-3 inline-flex items-center gap-2 font-bold text-[#6a1b9a]"><Share2 size={16}/> Share</button>{canManage&&<div className="mt-4 text-xs"><span className="hf-badge">{c.status}</span> <span className="hf-badge">order {c.sort_order}</span></div>}</div></article>)}</section>
 </div></AppLayout>
}
function Field({label,children}:{label:string;children:any}){return <div><label className="hf-label">{label}</label>{children}</div>}
