import { Head, useForm } from '@inertiajs/react';
import AppLayout from '../../layouts/app-layout';

export default function FamilyTime({schedules,completions,centers,canManage,canComplete}:any){
 const f=useForm({center_id:'',title:'',description:'',audience:'all',starts_at:'',ends_at:'',status:'active'});
 return <AppLayout title="Family Time"><Head title="Family Time"/><div className="grid gap-5 xl:grid-cols-[1fr_1fr]">
  <section className="space-y-4">{canManage&&<form className="hf-card p-5 space-y-3" onSubmit={e=>{e.preventDefault();f.post('/support/family-time/schedules',{onSuccess:()=>f.reset('title','description','starts_at','ends_at')})}}><h2 className="text-lg font-extrabold">Family Time schedule</h2><Field label="Center"><select className="hf-input" value={f.data.center_id} onChange={e=>f.setData('center_id',e.target.value)}><option value="">All Centers</option>{centers.map((c:any)=><option key={c.id} value={c.id}>{c.code} - {c.name}</option>)}</select></Field><Field label="Title"><input className="hf-input" value={f.data.title} onChange={e=>f.setData('title',e.target.value)}/></Field><Field label="Description"><textarea className="hf-input min-h-24" value={f.data.description} onChange={e=>f.setData('description',e.target.value)}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Starts"><input type="datetime-local" className="hf-input" value={f.data.starts_at} onChange={e=>f.setData('starts_at',e.target.value)}/></Field><Field label="Ends"><input type="datetime-local" className="hf-input" value={f.data.ends_at} onChange={e=>f.setData('ends_at',e.target.value)}/></Field></div><button className="hf-btn">Create Schedule</button></form>}
   <div className="space-y-3">{schedules.map((s:any)=><ScheduleCard key={s.id} schedule={s} canComplete={canComplete}/>)}</div>
  </section>
  <section className="hf-card p-5 overflow-x-auto"><h2 className="font-extrabold">Completion history</h2><table className="hf-table mt-3"><thead><tr><th>Date</th><th>Schedule</th><th>User</th><th>Center</th><th>Note</th></tr></thead><tbody>{completions.map((c:any)=><tr key={c.id}><td>{c.completed_on}</td><td>{c.schedule?.title??'-'}</td><td>{c.user?.name}</td><td>{c.center?.code??'-'}</td><td>{c.note??'-'}</td></tr>)}</tbody></table></section>
 </div></AppLayout>
}
function ScheduleCard({schedule,canComplete}:any){const f=useForm({completed_on:new Date().toISOString().slice(0,10),note:''});return <article className="hf-card p-5"><div className="flex flex-wrap justify-between gap-3"><div><span className="hf-badge">{schedule.center?.code??'All Centers'}</span><h2 className="mt-2 text-lg font-extrabold">{schedule.title}</h2></div><span className="hf-badge">{schedule.status}</span></div><p className="mt-2 text-sm text-[#5e4e63]">{schedule.description}</p><div className="mt-3 text-xs font-semibold text-[#78677e]">{new Date(schedule.starts_at).toLocaleString()}{schedule.ends_at?` - ${new Date(schedule.ends_at).toLocaleString()}`:''} · {schedule.completions_count} completions</div>{canComplete&&schedule.status==='active'&&<form className="mt-4 flex flex-col gap-2 sm:flex-row" onSubmit={e=>{e.preventDefault();f.post(`/support/family-time/schedules/${schedule.id}/complete`)}}><input type="date" className="hf-input sm:max-w-44" value={f.data.completed_on} onChange={e=>f.setData('completed_on',e.target.value)}/><input className="hf-input" placeholder="Optional note" value={f.data.note} onChange={e=>f.setData('note',e.target.value)}/><button className="hf-btn whitespace-nowrap">Mark Complete</button></form>}</article>}
function Field({label,children}:{label:string;children:any}){return <div><label className="hf-label">{label}</label>{children}</div>}
