import { Head, router, useForm } from '@inertiajs/react';
import AppLayout from '../../layouts/app-layout';

export default function Inventory({items,centers,canManage,filters}:any){
 const f=useForm({center_id:'',sku:'',name:'',unit:'pcs',minimum_stock:'0',status:'active'});
 return <AppLayout title="Inventory / Stock Register"><Head title="Inventory"/><div className="mb-4 flex flex-wrap items-center gap-2"><label className="hf-label mb-0">Center</label><select className="hf-input max-w-64" value={filters.center_id??''} onChange={e=>router.get('/support/inventory',e.target.value?{center_id:e.target.value}:{},{preserveState:true})}><option value="">All permitted Centers</option>{centers.map((c:any)=><option key={c.id} value={c.id}>{c.code} - {c.name}</option>)}</select></div><div className={canManage?'grid gap-5 xl:grid-cols-[380px_1fr]':''}>
 {canManage&&<form className="hf-card p-5 space-y-3" onSubmit={e=>{e.preventDefault();f.post('/support/inventory',{onSuccess:()=>f.reset('sku','name')})}}><h2 className="font-extrabold">Add inventory item</h2><Field label="Center"><select className="hf-input" value={f.data.center_id} onChange={e=>f.setData('center_id',e.target.value)}><option value="">Select Center</option>{centers.map((c:any)=><option key={c.id} value={c.id}>{c.code} - {c.name}</option>)}</select></Field><Field label="SKU"><input className="hf-input" value={f.data.sku} onChange={e=>f.setData('sku',e.target.value)}/></Field><Field label="Item"><input className="hf-input" value={f.data.name} onChange={e=>f.setData('name',e.target.value)}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Unit"><input className="hf-input" value={f.data.unit} onChange={e=>f.setData('unit',e.target.value)}/></Field><Field label="Minimum stock"><input type="number" min="0" className="hf-input" value={f.data.minimum_stock} onChange={e=>f.setData('minimum_stock',e.target.value)}/></Field></div><button className="hf-btn">Create Item</button></form>}
 <section className="space-y-4">{items.map((item:any)=><InventoryCard key={item.id} item={item} canManage={canManage}/>)}</section>
 </div></AppLayout>
}
function InventoryCard({item,canManage}:any){const f=useForm({transaction_type:'inward',quantity:'1',reference:'',note:''});const low=item.current_stock<=item.minimum_stock;return <article className="hf-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs font-bold text-[#7b5f87]">{item.center?.code} · {item.sku}</div><h2 className="text-lg font-black">{item.name}</h2></div><div className={`rounded-xl px-4 py-2 text-right ${low?'bg-amber-50 text-amber-800':'bg-[#f5edf8] text-[#5f187c]'}`}><div className="text-2xl font-black">{item.current_stock}</div><div className="text-xs font-bold">{item.unit} {low?'· Low stock':''}</div></div></div>{canManage&&<form className="mt-4 grid gap-2 md:grid-cols-[130px_120px_1fr_1fr_auto]" onSubmit={e=>{e.preventDefault();f.post(`/support/inventory/${item.id}/transactions`,{onSuccess:()=>f.reset('reference','note')})}}><select className="hf-input" value={f.data.transaction_type} onChange={e=>f.setData('transaction_type',e.target.value)}><option value="inward">Inward</option><option value="outward">Outward</option></select><input type="number" min="1" className="hf-input" value={f.data.quantity} onChange={e=>f.setData('quantity',e.target.value)}/><input className="hf-input" placeholder="Reference" value={f.data.reference} onChange={e=>f.setData('reference',e.target.value)}/><input className="hf-input" placeholder="Note" value={f.data.note} onChange={e=>f.setData('note',e.target.value)}/><button className="hf-btn">Record</button></form>}<div className="mt-4 overflow-x-auto"><div className="hf-table-scroll"><table className="hf-table hf-mobile-table"><thead><tr><th>When</th><th>Type</th><th>Qty</th><th>Before</th><th>After</th><th>By</th></tr></thead><tbody>{(item.transactions??[]).map((t:any)=><tr key={t.id}><td>{new Date(t.recorded_at).toLocaleString()}</td><td>{t.transaction_type}</td><td>{t.quantity}</td><td>{t.stock_before}</td><td>{t.stock_after}</td><td>{t.recorder?.name??'-'}</td></tr>)}</tbody></table></div></div></article>}
function Field({label,children}:{label:string;children:any}){return <div><label className="hf-label">{label}</label>{children}</div>}
