import { Head, Link } from '@inertiajs/react';
import { BarChart3, Filter } from 'lucide-react';
import AppLayout from '../../layouts/app-layout';

export default function BalAnalysis({analysis,options}:any){
 const s=analysis.summary; const maxTrend=Math.max(1,...analysis.completionTrend.map((r:any)=>r.completed));
 return <AppLayout title="Bal Pravruti Analysis"><Head title="Bal Analysis"/>
  <section className="hf-card mb-5 p-5"><div className="mb-4"><div className="text-xs font-bold uppercase tracking-[.14em] text-[#7b5f87]">{analysis.scopeLabel}</div><h2 className="text-xl font-black">Separate Bal Pravruti Dashboard & Analysis</h2></div><form method="get" action="/bal-pravruti/analysis" className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><Select name="center_id" label="Center" value={analysis.filters.center_id??''}><option value="">All permitted centers</option>{options.centers.map((c:any)=><option key={c.id} value={c.id}>{c.code} - {c.name}</option>)}</Select><Select name="gender" label="Sanchalak Gender" value={analysis.filters.gender??''} disabled={analysis.filters.female_scope_locked}><option value="">All</option><option value="male">Male</option><option value="female">Female</option></Select>{analysis.filters.female_scope_locked&&<input type="hidden" name="gender" value="female"/>}<Select name="category" label="Sanchalak Category" value={analysis.filters.category??''}><option value="">All categories</option>{options.categories.map((c:string)=><option key={c} value={c}>{c}</option>)}</Select><Field label="From"><input className="hf-input" name="date_from" type="date" defaultValue={analysis.filters.date_from??''}/></Field><Field label="To"><input className="hf-input" name="date_to" type="date" defaultValue={analysis.filters.date_to??''}/></Field><div className="flex items-end gap-2"><button className="hf-btn inline-flex items-center gap-2"><Filter size={16}/> Apply</button><Link href="/bal-pravruti/analysis" className="hf-btn hf-btn-secondary">Reset</Link></div></form></section>
  {analysis.filters.female_scope_locked&&<div className="mb-5 rounded-xl border border-fuchsia-200 bg-fuchsia-50 p-4 text-sm font-semibold text-fuchsia-900">BN Karyalay Bal analysis is server-side locked to Female Sanchalak scope.</div>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Bal Groups" value={s.activeGroups}/><Metric label="Children" value={s.children}/><Metric label="Families Visited" value={s.familiesVisited}/><Metric label="Families Completed" value={s.familiesCompleted}/><Metric label="Completion Reports" value={s.reports}/><Metric label="Sanchalaks" value={s.sanchalaks}/><Metric label="Visited→Completed" value={`${s.completionRate}%`}/><Metric label="Required Composition" value="3 + 1"/></div>
  <div className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="hf-card p-5"><div className="flex items-center gap-2"><BarChart3 size={18}/><h2 className="font-extrabold">Bal Completion Trend</h2></div><div className="mt-5 flex h-48 items-end gap-1 overflow-x-auto border-b border-[#eadff0] pb-1">{analysis.completionTrend.map((r:any)=><div key={r.date} className="flex min-w-[22px] flex-1 flex-col items-center justify-end gap-1" title={`${r.date}: ${r.completed}`}><div className="w-full rounded-t bg-[#7b2d96]" style={{height:`${Math.max(3,(r.completed/maxTrend)*150)}px`}}/><span className="hidden text-[9px] text-[#7b6b80] 2xl:block">{r.date.slice(5)}</span></div>)}</div></section><section className="hf-card p-5"><h2 className="font-extrabold">Children by Gender</h2><div className="mt-4 space-y-3">{analysis.childGenderDistribution.map((r:any)=><div key={r.key} className="rounded-xl bg-[#faf6fc] p-4"><div className="text-sm font-semibold">{r.label}</div><div className="mt-1 text-3xl font-black text-[#5f187c]">{r.value}</div></div>)}</div></section></div>
  <div className="mt-5 grid gap-5 xl:grid-cols-2"><Table title="Center Bal Analysis" rows={analysis.centerPerformance} columns={[['center','Center'],['groups','Groups'],['children','Children'],['families_visited','Visited'],['families_completed','Completed'],['completion_rate','Rate %']]}/><Table title="Zone Bal Analysis" rows={analysis.zonePerformance} columns={[['zone','Zone'],['centers','Centers'],['groups','Groups'],['families_visited','Visited'],['families_completed','Completed'],['completion_rate','Rate %']]}/></div>
  <section className="hf-card mt-5 p-5 overflow-x-auto"><h2 className="font-extrabold">Group Analysis</h2><table className="hf-table mt-3"><thead><tr><th>Group</th><th>Center</th><th>Sanchalak</th><th>Children</th><th>Reports</th><th>Visited</th><th>Completed</th><th>Last Completion</th></tr></thead><tbody>{analysis.groupPerformance.map((r:any)=><tr key={r.group_id}><td><Link className="font-bold text-[#6a1b9a]" href={`/bal-pravruti/groups/${r.group_id}`}>{r.group_code}</Link></td><td>{r.center}</td><td>{r.sanchalak}</td><td>{r.children}</td><td>{r.reports}</td><td>{r.families_visited}</td><td>{r.families_completed}</td><td>{r.last_completion_date??'-'}</td></tr>)}</tbody></table></section>
 </AppLayout>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="hf-card p-5"><div className="text-sm font-semibold text-[#7a657f]">{label}</div><div className="mt-2 text-3xl font-black text-[#5f187c]">{value}</div></div>}
function Field({label,children}:{label:string;children:any}){return <div><label className="hf-label">{label}</label>{children}</div>}
function Select({label,children,...props}:any){return <Field label={label}><select className="hf-input" {...props}>{children}</select></Field>}
function Table({title,rows,columns}:{title:string;rows:any[];columns:[string,string][]}){return <section className="hf-card p-5 overflow-x-auto"><h2 className="font-extrabold">{title}</h2><table className="hf-table mt-3"><thead><tr>{columns.map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{rows.map((r:any,i:number)=><tr key={i}>{columns.map(c=><td key={c[0]}>{r[c[0]]}</td>)}</tr>)}</tbody></table></section>}
