import { Head, Link } from '@inertiajs/react';
import { BarChart3, ClipboardCheck, UsersRound } from 'lucide-react';
import AppLayout from '../../layouts/app-layout';

export default function BalDashboard({bal,canManage,canSubmit,systemWarning}:any){
 const s=bal.summary;
 return <AppLayout title="Bal Pravruti Dashboard"><Head title="Bal Pravruti Dashboard"/>
  {systemWarning&&<div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-900">{systemWarning}</div>}
  <section className="hf-card mb-5 overflow-hidden"><div className="hf-brand p-5 text-white"><div className="text-xs font-bold uppercase tracking-[.16em] opacity-80">{bal.scopeLabel}</div><h2 className="mt-1 text-2xl font-black">Bal Pravruti - Happy Family</h2><p className="mt-1 text-sm opacity-85">Separate role-scoped dashboard for 3 children + 1 Sanchalak Groups and family completion reporting.</p></div>
   <div className="flex flex-wrap gap-2 p-4"><Link href="/bal-pravruti/groups" className="hf-btn hf-btn-secondary inline-flex items-center gap-2"><UsersRound size={17}/> Bal Groups</Link>{canSubmit&&<Link href="/bal-pravruti/completions" className="hf-btn inline-flex items-center gap-2"><ClipboardCheck size={17}/> Submit Completion</Link>}<Link href="/bal-pravruti/analysis" className="hf-btn hf-btn-secondary inline-flex items-center gap-2"><BarChart3 size={17}/> Analysis</Link></div>
  </section>
  {bal.filters.female_scope_locked&&<div className="mb-5 rounded-xl border border-fuchsia-200 bg-fuchsia-50 p-4 text-sm font-semibold text-fuchsia-900">BN Karyalay Bal analysis is locked to Female Sanchalak scope. Group administration remains available according to role permission.</div>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active Bal Groups" value={s.activeGroups}/><Metric label="Children Assigned" value={s.children}/><Metric label="Families Visited" value={s.familiesVisited}/><Metric label="Families Completed" value={s.familiesCompleted}/><Metric label="Sanchalaks" value={s.sanchalaks}/><Metric label="Completion Reports" value={s.reports}/><Metric label="Visited→Completed" value={`${s.completionRate}%`}/><Metric label="Group Rule" value="3 + 1"/></div>
  <div className="mt-5 grid gap-5 xl:grid-cols-2"><Performance title="Center Bal Performance" rows={bal.centerPerformance} keyName="center"/><Performance title="Zone Bal Performance" rows={bal.zonePerformance} keyName="zone"/></div>
  <section className="hf-card mt-5 p-5 overflow-x-auto"><div><h2 className="font-extrabold">Group progress</h2>{bal.groupPerformanceTruncated&&<p className="mt-1 text-xs text-amber-700">Showing first {bal.groupPerformanceLimit} groups for dashboard safety. Use Bal Groups pages for the full list.</p>}</div><div className="hf-table-scroll"><table className="hf-table hf-mobile-table mt-3"><thead><tr><th>Group</th><th>Center</th><th>Sanchalak</th><th>Children</th><th>Visited</th><th>Completed</th><th>Last Report</th></tr></thead><tbody>{bal.groupPerformance.map((r:any)=><tr key={r.group_id}><td><Link className="font-bold text-[#6a1b9a]" href={`/bal-pravruti/groups/${r.group_id}`}>{r.group_code}</Link></td><td>{r.center}</td><td>{r.sanchalak}</td><td>{r.children}</td><td>{r.families_visited}</td><td>{r.families_completed}</td><td>{r.last_completion_date??'-'}</td></tr>)}</tbody></table></div></section>
 </AppLayout>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="hf-card p-5"><div className="text-sm font-semibold text-[#7a657f]">{label}</div><div className="mt-2 text-3xl font-black text-[#5f187c]">{value}</div></div>}
function Performance({title,rows,keyName}:{title:string;rows:any[];keyName:string}){return <section className="hf-card p-5"><h2 className="font-extrabold">{title}</h2><div className="mt-3 space-y-3">{rows.length===0?<div className="text-sm text-[#74677a]">No Bal Pravruti data yet.</div>:rows.map((r:any)=><div key={String(r[`${keyName}_id`]??r[keyName])} className="rounded-xl bg-[#faf6fc] p-3"><div className="flex justify-between gap-3"><div><div className="font-bold">{r[keyName]}</div><div className="text-xs text-[#796a7d]">{r.groups} groups · {r.families_visited} visited · {r.families_completed} completed</div></div><div className="font-black text-[#5f187c]">{r.completion_rate}%</div></div><div className="mt-2 h-2 rounded-full bg-[#eee5f1]"><div className="h-2 rounded-full bg-[#6a1b9a]" style={{width:`${Math.min(100,r.completion_rate)}%`}}/></div></div>)}</div></section>}
