import { Head, Link, useForm } from '@inertiajs/react';
import AppLayout from '../../layouts/app-layout';

export default function BalGroups({groups,options,canManage}:any){
 const f=useForm({center_id:'',sampark_area_id:'',society_id:'',sanchalak_karyakar_id:'',child_member_ids:['','',''],nirdeshak_user_id:'',nirikshak_user_id:''});
 const centerId=String(f.data.center_id);
 const areas=(options?.areas??[]).filter((x:any)=>String(x.center_id)===centerId);
 const societies=(options?.societies??[]).filter((x:any)=>String(x.center_id)===centerId&&(!f.data.sampark_area_id||String(x.sampark_area_id)===String(f.data.sampark_area_id)));
 const children=(options?.children??[]).filter((x:any)=>String(x.center_id)===centerId);
 const sanchalaks=(options?.sanchalaks??[]).filter((x:any)=>String(x.center_id)===centerId);
 const supervisors=(role:string)=>(options?.supervisors??[]).filter((u:any)=>u.roles.some((r:any)=>r.slug===role&&String(r.center_id)===centerId));
 const setChild=(index:number,value:string)=>{const next=[...f.data.child_member_ids];next[index]=value;f.setData('child_member_ids',next)};
 return <AppLayout title="Bal Pravruti Groups"><Head title="Bal Groups"/>
  <div className={canManage?'grid gap-5 2xl:grid-cols-[460px_1fr]':''}>
   {canManage&&<form className="hf-card p-5 space-y-3" onSubmit={e=>{e.preventDefault();f.post('/bal-pravruti/groups')}}><div><div className="text-xs font-bold uppercase tracking-[.14em] text-[#7b5f87]">Exact composition rule</div><h2 className="text-lg font-extrabold">Create 3 Children + 1 Sanchalak Group</h2></div>
    <Field label="Center"><select className="hf-input" value={f.data.center_id} onChange={e=>{f.setData('center_id',e.target.value);f.setData('sampark_area_id','');f.setData('society_id','');f.setData('sanchalak_karyakar_id','');f.setData('child_member_ids',['','','']);f.setData('nirdeshak_user_id','');f.setData('nirikshak_user_id','')}}><option value="">Select Center</option>{options?.centers.map((c:any)=><option key={c.id} value={c.id}>{c.code} - {c.name}</option>)}</select></Field>
    <div className="grid grid-cols-2 gap-3"><Field label="Sampark Area"><select className="hf-input" value={f.data.sampark_area_id} onChange={e=>{f.setData('sampark_area_id',e.target.value);f.setData('society_id','')}}><option value="">Optional</option>{areas.map((a:any)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="Society"><select className="hf-input" value={f.data.society_id} onChange={e=>f.setData('society_id',e.target.value)}><option value="">Optional</option>{societies.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field></div>
    <Field label="Sanchalak (Approved Sankalp Karyakar)"><select className="hf-input" value={f.data.sanchalak_karyakar_id} onChange={e=>f.setData('sanchalak_karyakar_id',e.target.value)}><option value="">Select linked Sanchalak</option>{sanchalaks.map((k:any)=><option key={k.id} value={k.id}>{k.full_name} · {k.gender} · {k.category}</option>)}</select></Field>
    {[0,1,2].map(i=><Field key={i} label={`Child ${i+1} (Age 0-12)`}><select className="hf-input" value={f.data.child_member_ids[i]} onChange={e=>setChild(i,e.target.value)}><option value="">Select child</option>{children.map((c:any)=><option key={c.id} value={c.id}>{c.name} · {c.gender} · age {c.age} · {c.family_reference??c.family_head}</option>)}</select></Field>)}
    <div className="grid grid-cols-2 gap-3"><Field label="Nirdeshak"><select className="hf-input" value={f.data.nirdeshak_user_id} onChange={e=>f.setData('nirdeshak_user_id',e.target.value)}><option value="">Optional</option>{supervisors('nirdeshak').map((u:any)=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Nirikshak"><select className="hf-input" value={f.data.nirikshak_user_id} onChange={e=>f.setData('nirikshak_user_id',e.target.value)}><option value="">Optional</option>{supervisors('nirikshak').map((u:any)=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field></div>
    {Object.keys(f.errors).length>0&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{Object.values(f.errors).join(' ')}</div>}<button className="hf-btn" disabled={f.processing}>Create Bal Group</button>
   </form>}
   <section className="hf-card p-5 overflow-x-auto"><div className="mb-3 flex items-center justify-between gap-3"><div><h2 className="font-extrabold">Accessible Bal Groups</h2><p className="text-xs text-[#78677e]">Nirdeshak/Nirikshak see assigned Groups; Sanchalak sees own Groups.</p></div><Link href="/bal-pravruti" className="hf-btn hf-btn-secondary">Dashboard</Link></div><table className="hf-table"><thead><tr><th>Group</th><th>Center</th><th>Sanchalak</th><th>Children</th><th>Supervision</th><th>Reports</th><th>Status</th></tr></thead><tbody>{groups.map((g:any)=><tr key={g.id}><td><Link href={`/bal-pravruti/groups/${g.id}`} className="font-bold text-[#6a1b9a]">{g.group_code}</Link></td><td>{g.center?.name}</td><td>{g.sanchalak?.full_name}<div className="text-xs text-[#78677e]">{g.sanchalak?.category}</div></td><td>{g.children_count} / 3</td><td>{g.supervisors.length?g.supervisors.map((s:any)=><div key={`${s.role_slug}-${s.user.id}`} className="text-xs"><b>{s.role_slug}:</b> {s.user.name}</div>):'-'}</td><td>{g.completion_reports_count}</td><td><span className="hf-badge">{g.status}</span></td></tr>)}</tbody></table></section>
  </div>
 </AppLayout>;
}
function Field({label,children}:{label:string;children:any}){return <div><label className="hf-label">{label}</label>{children}</div>}
