import { Head, Link } from '@inertiajs/react';
import { Phone } from 'lucide-react';
import AppLayout from '../../layouts/app-layout';

export default function BalGroupDetail({group}:any){return <AppLayout title={`Bal Group ${group.group_code}`}><Head title={group.group_code}/>
 <section className="hf-card overflow-hidden"><div className="hf-brand p-5 text-white"><div className="text-xs font-bold uppercase tracking-[.15em] opacity-80">{group.center?.name}</div><div className="mt-1 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-black">{group.group_code}</h2><p className="text-sm opacity-85">Exactly 3 children + 1 assigned Sanchalak</p></div><span className="rounded-full bg-white/15 px-3 py-1 text-sm font-bold">{group.status}</span></div></div>
  <div className="grid gap-4 p-5 md:grid-cols-3"><Info label="Area" value={group.area?.name??'-'}/><Info label="Society" value={group.society?.name??'-'}/><Info label="Activated" value={group.activated_at?.slice(0,10)??'-'}/></div></section>
 <div className="mt-5 grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
  <section className="hf-card p-5"><h2 className="font-extrabold">Sanchalak</h2><div className="mt-3 rounded-xl bg-[#faf6fc] p-4"><div className="font-bold">{group.sanchalak?.full_name}</div><div className="text-sm text-[#76677b]">{group.sanchalak?.gender} · {group.sanchalak?.category}</div>{group.sanchalak?.mobile&&<a className="mt-3 inline-flex items-center gap-2 font-bold text-[#6a1b9a]" href={`tel:${group.sanchalak.mobile}`}><Phone size={16}/> {group.sanchalak.mobile}</a>}</div><h3 className="mt-5 text-sm font-extrabold">Assigned supervision</h3><div className="mt-2 space-y-2">{group.supervisors.filter((s:any)=>s.status==='active').map((s:any)=><div key={s.id} className="rounded-xl border border-[#eadff0] p-3"><div className="text-xs font-bold uppercase text-[#7b5f87]">{s.role_slug}</div><div className="font-semibold">{s.user?.name}</div></div>)}</div></section>
  <section className="hf-card p-5"><h2 className="font-extrabold">3 Children</h2><div className="mt-3 grid gap-3 md:grid-cols-3">{group.children.filter((c:any)=>c.status==='active').map((c:any)=><div key={c.id} className="rounded-xl bg-[#faf6fc] p-4"><div className="text-xs font-black text-[#6a1b9a]">Child {c.position}</div><div className="mt-1 font-bold">{c.member?.name}</div><div className="text-sm text-[#76677b]">{c.member?.gender} · Age {c.member?.age}</div><div className="mt-2 text-xs">Family: {c.member?.family?.external_family_id??c.member?.family?.manual_reference??c.member?.family?.head_name}</div></div>)}</div></section>
 </div>
 <section className="hf-card mt-5 p-5 overflow-x-auto"><div className="mb-3 flex items-center justify-between"><h2 className="font-extrabold">Completion Report History</h2><Link href="/bal-pravruti/analysis" className="hf-btn hf-btn-secondary">Analysis</Link></div><div className="hf-table-scroll"><table className="hf-table hf-mobile-table"><thead><tr><th>Date</th><th>Society</th><th>Family</th><th>Visited</th><th>Completed</th><th>Mobile</th><th>Details</th><th>Submitted By</th></tr></thead><tbody>{group.completion_reports.map((r:any)=><tr key={r.id}><td>{String(r.completion_date).slice(0,10)}</td><td>{r.society?.name??'-'}</td><td>{r.family?.head_name??r.family_name??'-'}</td><td>{r.families_visited}</td><td>{r.families_completed}</td><td>{r.mobile??'-'}</td><td className="max-w-sm whitespace-pre-wrap">{r.family_details}</td><td>{r.submitted_by?.name??'-'}</td></tr>)}</tbody></table></div></section>
 </AppLayout>}
function Info({label,value}:{label:string;value:string}){return <div><div className="text-xs font-bold uppercase tracking-wide text-[#7b657f]">{label}</div><div className="mt-1 font-bold">{value}</div></div>}
