import AppLayout from '../../layouts/app-layout';
import { Link, useForm } from '@inertiajs/react';
import { Plus, Trash2 } from 'lucide-react';

type Member={id:number|null;external_member_id:string|null;name:string;gender:'male'|'female';age:number|string|null;mobile:string|null;relationship:string|null;is_head:boolean;status:string};
type Family={id:number;external_family_id:string|null;manual_reference:string|null;source:string;head_name:string;head_mobile:string|null;address:string|null;city_village:string|null;status:string;sampark_area_id:number|null;society_id:number|null;center:{name:string;code:string};area?:{name:string}|null;society?:{name:string}|null;members:Member[]};
type Area={id:number;name:string};
type Society={id:number;sampark_area_id:number|null;name:string};

export default function FamilyDetail({family,areas,societies}:{family:Family;areas:Area[];societies:Society[]}){
    const f=useForm({
        head_name:family.head_name,head_mobile:family.head_mobile??'',address:family.address??'',city_village:family.city_village??'',
        sampark_area_id:family.sampark_area_id?String(family.sampark_area_id):'',society_id:family.society_id?String(family.society_id):'',status:family.status,
        change_reason:'',members:family.members.map(m=>({...m,age:m.age??'',mobile:m.mobile??'',relationship:m.relationship??'',status:m.status??'active'})),
    });
    const relevantSocieties=societies.filter(s=>String(s.sampark_area_id??'')===f.data.sampark_area_id);
    const updateMember=(i:number,patch:Partial<Member>)=>f.setData('members',f.data.members.map((m,j)=>j===i?{...m,...patch}:m));
    const addMember=()=>f.setData('members',[...f.data.members,{id:null,external_member_id:null,name:'',gender:'male',age:'',mobile:'',relationship:'',is_head:false,status:'active'}]);
    return <AppLayout title="Family Detail"><div className="max-w-6xl space-y-5">
        <div className="hf-card p-5"><div className="flex justify-between gap-3"><div><div className="text-xs uppercase font-bold text-[#7a6584]">Family Reference</div><h2 className="text-2xl font-extrabold">{family.external_family_id??family.manual_reference}</h2></div><Link className="hf-btn hf-btn-secondary h-fit" href="/registration/families">Back</Link></div><div className="grid md:grid-cols-3 gap-4 mt-5 text-sm"><div><b>Head:</b> {family.head_name}<br/><b>Mobile:</b> {family.head_mobile?<a className="font-bold text-[#6a1b9a]" href={`tel:${family.head_mobile}`}>{family.head_mobile}</a>:'-'}</div><div><b>Center:</b> {family.center.code} - {family.center.name}<br/><b>Source:</b> {family.source}</div><div><b>Area:</b> {family.area?.name??'-'}<br/><b>Society:</b> {family.society?.name??'-'}</div></div><div className="mt-4 text-sm"><b>Address:</b> {family.address??'-'} {family.city_village?`- ${family.city_village}`:''}</div></div>

        <form className="hf-card p-5 space-y-4" onSubmit={e=>{e.preventDefault();f.put(`/registration/families/${family.id}`,{preserveScroll:true,onSuccess:()=>f.setData('change_reason','')})}}>
            <div><h3 className="font-extrabold text-lg">Edit Family Details</h3><p className="text-sm text-[#76647e]">All changes are Center-scoped and require a reason for the audit log. Family ID/source and Center cannot be changed here.</p></div>
            <div className="grid gap-3 md:grid-cols-2"><Field label="Head of Family" error={f.errors.head_name}><input className="hf-input" value={f.data.head_name} onChange={e=>f.setData('head_name',e.target.value)} required/></Field><Field label="Head Mobile" error={f.errors.head_mobile}><input className="hf-input" value={f.data.head_mobile} onChange={e=>f.setData('head_mobile',e.target.value)}/></Field></div>
            <div className="grid gap-3 md:grid-cols-2"><Field label="City / Village" error={f.errors.city_village}><input className="hf-input" value={f.data.city_village} onChange={e=>f.setData('city_village',e.target.value)}/></Field><Field label="Status" error={f.errors.status}><select className="hf-input" value={f.data.status} onChange={e=>f.setData('status',e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option>{family.source==='karyakar_reported'&&<option value="pending_verification">Pending Verification</option>}</select></Field></div>
            <Field label="Address" error={f.errors.address}><textarea className="hf-input" rows={2} value={f.data.address} onChange={e=>f.setData('address',e.target.value)}/></Field>
            <div className="grid gap-3 md:grid-cols-2"><Field label="Sampark Area" error={f.errors.sampark_area_id}><select className="hf-input" value={f.data.sampark_area_id} onChange={e=>{f.setData(data=>({...data,sampark_area_id:e.target.value,society_id:''}))}}><option value="">-</option>{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="Society" error={f.errors.society_id}><select className="hf-input" value={f.data.society_id} onChange={e=>f.setData('society_id',e.target.value)}><option value="">-</option>{relevantSocieties.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field></div>

            <div className="border-t border-[#eadff0] pt-4"><div className="flex items-center justify-between gap-3"><div><h3 className="font-extrabold">Family Members</h3><p className="text-xs text-[#76647e]">Existing imported Member IDs are preserved. Members can be updated or marked inactive; new members can be added.</p></div><button type="button" className="hf-btn hf-btn-secondary" onClick={addMember}><Plus size={15} className="inline"/> Add Member</button></div>{f.errors.members&&<ErrorText text={f.errors.members}/>}<div className="mt-3 space-y-3">{f.data.members.map((m,i)=><div key={m.id??`new-${i}`} className="rounded-xl border border-[#eadff0] bg-[#faf7fc] p-3"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-bold text-[#78677e]">{m.external_member_id?`Member ID: ${m.external_member_id}`:m.id?'Portal member':'New member'}</span>{m.id===null&&<button type="button" className="text-[#7a366f]" onClick={()=>f.setData('members',f.data.members.filter((_,j)=>j!==i))}><Trash2 size={16}/></button>}</div><div className="grid gap-2 md:grid-cols-6"><input className="hf-input md:col-span-2" placeholder="Name" value={m.name} onChange={e=>updateMember(i,{name:e.target.value})}/><select className="hf-input" value={m.gender} onChange={e=>updateMember(i,{gender:e.target.value as 'male'|'female'})}><option value="male">Male</option><option value="female">Female</option></select><input className="hf-input" type="number" min="0" max="120" placeholder="Age" value={m.age??''} onChange={e=>updateMember(i,{age:e.target.value})}/><input className="hf-input" placeholder="Mobile" value={m.mobile??''} onChange={e=>updateMember(i,{mobile:e.target.value})}/><select className="hf-input" value={m.status} onChange={e=>updateMember(i,{status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div className="mt-2 grid gap-2 md:grid-cols-[1fr_auto]"><input className="hf-input" placeholder="Relationship" value={m.relationship??''} onChange={e=>updateMember(i,{relationship:e.target.value})}/><label className="flex items-center gap-2 rounded-lg border border-[#e5d8eb] bg-white px-3 text-xs"><input type="checkbox" checked={m.is_head} onChange={e=>f.setData('members',f.data.members.map((x,j)=>({...x,is_head:j===i?e.target.checked:false})))}/> Head member</label></div></div>)}</div></div>
            <Field label="Required Change Reason / Note" error={f.errors.change_reason}><textarea className="hf-input" rows={2} placeholder="Why is this Family record being changed?" value={f.data.change_reason} onChange={e=>f.setData('change_reason',e.target.value)} required/></Field>
            <div className="flex justify-end"><button className="hf-btn" disabled={f.processing}>Save Audited Changes</button></div>
        </form>
    </div></AppLayout>;
}
function Field({label,error,children}:{label:string;error?:string;children:any}){return <div><label className="hf-label">{label}</label>{children}{error&&<ErrorText text={error}/>}</div>}
function ErrorText({text}:{text:string}){return <div className="mt-1 text-xs font-semibold text-red-700">{text}</div>}
