import { Head, Link } from '@inertiajs/react';
import { Filter } from 'lucide-react';
import AppLayout from '../../layouts/app-layout';

type Props={logs:any[];filters:Record<string,string>;options:{centers:any[];modules:string[];actions:string[];roles:string[]}};
export default function AuditLogs({logs,filters,options}:Props){return <AppLayout title="Activity / Audit Logs"><Head title="Audit Logs"/>
    <section className="hf-card mb-5 p-5"><div className="mb-4"><div className="text-xs font-bold uppercase tracking-[.15em] text-[#7b5f87]">Traceability</div><h2 className="text-xl font-black">Audit search & change details</h2><p className="mt-1 text-sm text-[#74667a]">Filter permitted log entries by Center, module, action, role, date or reference. Field-level roles see only their own relevant actions.</p></div><form method="get" action="/admin/audit-logs" className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div><label className="hf-label">Search</label><input className="hf-input" name="search" defaultValue={filters.search??''} placeholder="User, reference, reason..."/></div><Select name="center_id" label="Center" value={filters.center_id??''}><option value="">All permitted</option>{options.centers.map(c=><option key={c.id} value={c.id}>{c.name} ({c.code})</option>)}</Select><Select name="module" label="Module" value={filters.module??''}><option value="">All modules</option>{options.modules.map(v=><option key={v}>{v}</option>)}</Select><Select name="action" label="Action" value={filters.action??''}><option value="">All actions</option>{options.actions.map(v=><option key={v}>{v}</option>)}</Select><Select name="user_role" label="Role" value={filters.user_role??''}><option value="">All roles</option>{options.roles.map(v=><option key={v}>{v}</option>)}</Select><div><label className="hf-label">From</label><input className="hf-input" type="date" name="date_from" defaultValue={filters.date_from??''}/></div><div><label className="hf-label">To</label><input className="hf-input" type="date" name="date_to" defaultValue={filters.date_to??''}/></div><div className="flex items-end gap-2"><button className="hf-btn inline-flex items-center gap-2"><Filter size={16}/> Apply</button><Link href="/admin/audit-logs" className="hf-btn hf-btn-secondary">Reset</Link></div></form></section>
    <div className="hf-card p-5 overflow-x-auto"><div className="hf-table-scroll"><table className="hf-table hf-mobile-table"><thead><tr><th>Date</th><th>User / Role</th><th>Center</th><th>Module</th><th>Action</th><th>Reference</th><th>Old Value</th><th>New Value</th><th>Reason</th></tr></thead><tbody>{logs.length===0?<tr><td colSpan={9}>No audit entries found.</td></tr>:logs.map((l:any)=><tr key={l.id}><td>{formatDate(l.created_at)}</td><td><div className="font-semibold">{l.user_name??'-'}</div><div className="text-xs text-[#76677b]">{l.user_role??'-'}</div></td><td>{l.center?.name??l.center_id??'-'}</td><td>{l.module??'-'}</td><td>{l.action??'-'}</td><td>{l.record_reference??l.record_id??'-'}</td><td><JsonValue value={l.old_values}/></td><td><JsonValue value={l.new_values}/></td><td>{l.reason??'-'}</td></tr>)}</tbody></table></div></div>
</AppLayout>}
function Select({label,children,...props}:any){return <div><label className="hf-label">{label}</label><select className="hf-input" {...props}>{children}</select></div>}
function JsonValue({value}:{value:any}){if(!value||Object.keys(value).length===0)return <>-</>;return <details className="min-w-[180px]"><summary className="cursor-pointer font-semibold text-[#6a1b9a]">View changes</summary><pre className="mt-2 max-w-[360px] whitespace-pre-wrap rounded-lg bg-[#f8f3fa] p-2 text-xs">{JSON.stringify(value,null,2)}</pre></details>}
function formatDate(value:any){if(!value)return '-';return String(value).replace('T',' ').replace(/\.\d+Z$/,'')}
